name = "template"
main = "src/worker.ts"
tsconfig = "./tsconfig.json"
compatibility_date = "2025-02-14"

[assets]
directory = "./frontend/dist"
binding = "ASSETS"

[build]
command = "npm run build:frontend"
watch_dir = ["frontend", "src"]
